version: 2
updates:
  - package-ecosystem: pub
    directories: ['/jewish_date', '/jewish_holidays', '/jewish_zmanim']
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
