name: jewish_core_workspace
publish_to: none

environment:
  sdk: ^3.9.0

workspace:
  - packages/jewish_date
  - packages/jewish_holidays
  - packages/jewish_zmanim

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.0
